new

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -38,6 +38,8 @@ jobs:
 
       - name: Publish Image to Docker Hub
         run: docker push sumitdev99/reactjs-app:latest
+      - name: Debug - Check Build Directory
+        run: ls -la ./build || echo "Build folder missing!"
 
   deploy:
     needs: build
