aaaa

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -39,7 +39,7 @@ jobs:
       - name: Publish Image to Docker Hub
         run: docker push sumitdev99/reactjs-app:latest
       - name: Debug - Check Build Directory
-        run: ls -la ./build || echo "Build folder missing!"
+        run: ls -la ./dist || echo "⚠️ dist folder is missing!"
 
   deploy:
     needs: build
